// ===========================================================================
//  Cost of living — Abu Dhabi lifestyle re-priced into each district.
//
//  The family's actual Abu Dhabi household budget is the BASE. For every
//  district we multiply each budget line by a per-category ratio derived from
//  Numbeo's city indices (NYC=100), anchored on Abu Dhabi. The data is
//  generated by `src/scripts/rescore/build-cost-of-living.mjs` (was prototyped
//  in scratchpad) into `cost-of-living.generated.json`. Lookup is by district id.
//
//  Ratio rules per line:
//    rent       → Numbeo Rent index
//    grocery    → Groceries index        restaurant → Restaurant Price index
//    col        → general Cost-of-Living index (utilities, comms, transport, …)
//    help       → per-country full-time domestic-help cost floor (maid, governess)
//    flat       → not localised (car, travel, health, subscriptions) → ×1.00
//    (rent is computed but excluded from the total — housing is a separate decision)
// ===========================================================================

import raw from './cost-of-living.data.json';

export type CostRule = 'rent' | 'grocery' | 'restaurant' | 'col' | 'help' | 'flat';

interface CostMeta {
  anchor: string;
  source: string;
  fx_aed_per_eur: number;
  ad_monthly_aed: number;
  ad_monthly_eur: number;
  category_rules: Record<string, { ad_aed: number; rule: CostRule; category: string; excluded?: boolean }>;
}
interface CostEntry {
  id: string;
  city: string;
  country: string;
  numbeo_city: string;
  fallback: string | null;
  ratios: Record<string, number>;
  overall_multiplier: number;
  converted_aed_month: number;
  converted_eur_month: number;
}

const data = raw as { meta: CostMeta; districts: CostEntry[] };
export const COST_META = data.meta;

const byId = new Map<string, CostEntry>(data.districts.map((d) => [d.id, d]));

/** Human label per budget line, in the order shown. */
export const COST_CATEGORY_LABELS: Record<string, string> = {
  rent: 'Rent',
  utilities: 'Utilities',
  internet_phone: 'Internet / phone',
  groceries: 'Groceries',
  home_equipment: 'Home equipment',
  car_payment: 'Car',
  car_insurance: 'Car insurance',
  fuel: 'Fuel',
  taxi_transfers: 'Taxi & transfers',
  maid: 'Maid',
  governess: 'Governess',
  restaurants: 'Restaurants',
  activities: 'Activities',
  travel: 'Travel',
  health: 'Health',
  subscriptions: 'Subscriptions',
  shopping: 'Shopping',
};

/** Short tag explaining which index drove a line's ratio. */
export const COST_RULE_LABELS: Record<CostRule, string> = {
  rent: 'rent index',
  grocery: 'groceries index',
  restaurant: 'restaurant index',
  col: 'cost-of-living index',
  help: 'local help-cost',
  flat: 'not localised',
};

export interface CostLine {
  key: string;
  label: string;
  rule: CostRule;
  /** Abu Dhabi monthly spend, in EUR (converted from the AED budget). */
  adEur: number;
  /** Per-category multiplier vs Abu Dhabi. */
  ratio: number;
  /** Re-priced monthly spend in this district, in EUR. */
  hereEur: number;
  /** Budget group: Home | Transport | Staff | Lifestyle. */
  category: string;
  /** Excluded from the monthly-cost total (e.g. rent — housing is a separate decision). */
  excluded: boolean;
}

/** Lines grouped by budget category (Home / Transport / Staff / Lifestyle), excluded lines dropped. */
export interface CostGroup {
  category: string;
  adEur: number;
  hereEur: number;
  ratio: number;
  lines: CostLine[];
}

export interface CostBreakdown {
  /** Numbeo city actually used (may be a nearest-metro fallback). */
  numbeoCity: string;
  /** Set when numbeoCity is a fallback for a town Numbeo doesn't survey. */
  fallbackFrom: string | null;
  adEur: number;
  hereEur: number;
  multiplier: number;
  lines: CostLine[];
  /** Same lines grouped by budget category, excluded lines dropped — for the grouped UI. */
  groups: CostGroup[];
}

/** Overall €/mo of the Abu Dhabi lifestyle re-priced into a district (or null). */
export function getMonthlyCostEur(id: string): number | null {
  return byId.get(id)?.converted_eur_month ?? null;
}

/** Overall cost multiplier vs Abu Dhabi for a district (or null if unknown). */
export function getCostMultiplier(id: string): number | null {
  return byId.get(id)?.overall_multiplier ?? null;
}

/** Full per-category breakdown for the expanded detail panel (or null). */
export function getCostBreakdown(id: string): CostBreakdown | null {
  const e = byId.get(id);
  if (!e) return null;
  const fx = COST_META.fx_aed_per_eur;
  const lines: CostLine[] = Object.entries(COST_META.category_rules).map(([key, { ad_aed, rule, category, excluded }]) => {
    const adEur = ad_aed / fx;
    const ratio = e.ratios[key] ?? 1;
    return {
      key,
      label: COST_CATEGORY_LABELS[key] ?? key,
      rule,
      adEur,
      ratio,
      hereEur: adEur * ratio,
      category,
      excluded: !!excluded,
    };
  });
  // Group by category in first-appearance order; drop excluded lines (e.g. rent).
  const groups: CostGroup[] = [];
  for (const l of lines) {
    if (l.excluded) continue;
    let g = groups.find((x) => x.category === l.category);
    if (!g) { g = { category: l.category, adEur: 0, hereEur: 0, ratio: 1, lines: [] }; groups.push(g); }
    g.lines.push(l);
    g.adEur += l.adEur;
    g.hereEur += l.hereEur;
  }
  for (const g of groups) g.ratio = g.adEur > 0 ? g.hereEur / g.adEur : 1;
  return {
    numbeoCity: e.numbeo_city,
    fallbackFrom: e.fallback,
    adEur: COST_META.ad_monthly_eur,
    hereEur: e.converted_eur_month,
    multiplier: e.overall_multiplier,
    lines,
    groups,
  };
}
